name: ad_turbo
description: ad_turbo Implements Google Ads, Easy and fastest way, supporting All Type of Google Ads,Native Ads(Android) included.
version: 0.0.6
homepage: https://github.com/hardikkhunt905/ad_turbo.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
  google_mobile_ads: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ad_turbo
        pluginClass: AdTurboPlugin
      ios:
        pluginClass: AdTurboPlugin